if UnitClassBase("player") ~= "DEATHKNIGHT" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "符文" },
        [22] = { type = "block", name = "目标生命值" },
        [23] = { type = "block", name = "敌人人数" },

        [40] = { type = "spell", spellId = 49576, name = "死亡之握" },
        [41] = { type = "spell", spellId = 51052, name = "反魔法领域" },
        [42] = { type = "spell", spellId = 221562, name = "窒息" },
        [43] = { type = "spell", spellId = 207167, name = "致盲冰雨" },

        [44] = { type = "spell", spellId = 46585, name = "亡者复生" },
        [45] = { type = "spell", spellId = 55233, name = "吸血鬼之血" },
        [46] = { type = "spell", spellId = 48792, name = "冰封之韧" },
        [47] = { type = "spell", spellId = 49039, name = "巫妖之躯" },
        [48] = { type = "spell", spellId = 108199, name = "血魔之握" },
        [49] = { type = "spell", spellId = 1263569, name = "憎恶附肢" },
        [50] = { type = "spell", spellId = 50, name = "吞噬" },
    },
    [2] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "符文" },
        [22] = { type = "block", name = "目标生命值" },
        [23] = { type = "block", name = "敌人人数" },

        [24] = { type = "aura", name = "黑暗援助", auraName = "黑暗援助", showKey = "remaining" },
        [25] = { type = "aura", name = "杀戮机器", auraName = "杀戮机器", showKey = "count" },
        [26] = { type = "aura", name = "白霜", auraName = "白霜", showKey = "remaining" },
        [27] = { type = "aura", name = "锋锐", auraName = "锋锐", showKey = "remaining" },


        [40] = { type = "spell", spellId = 49576, name = "死亡之握" },
        [41] = { type = "spell", spellId = 51052, name = "反魔法领域" },
        [42] = { type = "spell", spellId = 221562, name = "窒息" },
        [43] = { type = "spell", spellId = 207167, name = "致盲冰雨" },
        [44] = { type = "spell", spellId = 51271, name = "冰柱" },
        [45] = { type = "spell", spellId = 279302, name = "冰龙" },
        [46] = { type = "spell", spellId = 439843, name = "死神" },
        [47] = { type = "spell", spellId = 47568, name = "符文武器" },
        [48] = { type = "spell", spellId = 47568, name = "符文武器", charge = true },
    },
    [3] = {
        ["countBars"] = {
            { valueType = "castCount", name = "天灾打击", minValue = 0, maxValue = 20, spellId = 55090 },
            { valueType = "charge", name = "腐化", minValue = 0, maxValue = 3, spellId = 1247378 },
            { valueType = "charge", name = "枯萎凋零", minValue = 0, maxValue = 2, spellId = 43265 }
        },

        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "符文" },
        [22] = { type = "block", name = "目标生命值" },
        [23] = { type = "block", name = "敌人人数" },

        [24] = { type = "block", name = "爆发开关" },
        [25] = { type = "block", name = "输出模式" },
        [26] = { type = "block", name = "AOE开关" },
        [30] = { type = "block", name = "爆发药水开关" },
        [32] = { type = "block", name = "目标距离" },

        [27] = { type = "block", name = "疾病判断" },
        [28] = { type = "block", name = "鲁莽药水冷却" },
        [29] = { type = "block", name = "大红冷却" },
        [31] = { type = "block", name = "延迟" },

        [41] = { type = "aura", name = "次级食尸鬼", auraName = "次级食尸鬼", showKey = "remaining" },
        [42] = { type = "aura", name = "割魂索命", auraName = "割魂索命", showKey = "remaining" },
        [43] = { type = "aura", name = "末日突降", auraName = "末日突降", showKey = "remaining" },
        [44] = { type = "aura", name = "末日突降层数", auraName = "末日突降", showKey = "count" },
        [45] = { type = "aura", name = "黑暗援助", auraName = "黑暗援助", showKey = "remaining" },
        [46] = { type = "aura", name = "禁断知识", auraName = "禁断知识", showKey = "remaining" },
        [47] = { type = "aura", name = "脓疮毒镰", auraName = "脓疮毒镰", showKey = "remaining" },
        [48] = { type = "aura", name = "脓疮毒镰2", auraName = "脓疮毒镰2", showKey = "remaining" },
        [49] = { type = "aura", name = "枯萎凋零", auraName = "枯萎凋零", showKey = "remaining" },
        [50] = { type = "aura", name = "亡者指挥官", auraName = "亡者指挥官", showKey = "remaining" },
        [51] = { type = "aura", name = "寒冰锁链", auraName = "寒冰锁链", showKey = "remaining" },
        [52] = { type = "aura", name = "暗影之爪层数", auraName = "暗影之爪", showKey = "count" },
        [53] = { type = "aura", name = "凋萎", auraName = "凋萎", showKey = "remaining" },

        [61] = { type = "spell", spellId = 49576, name = "死亡之握" },
        [62] = { type = "spell", spellId = 51052, name = "反魔法领域" },
        [63] = { type = "spell", spellId = 221562, name = "窒息" },
        [64] = { type = "spell", spellId = 207167, name = "致盲冰雨" },
        [65] = { type = "spell", spellId = 46584, name = "亡者复生" },
        [66] = { type = "spell", spellId = 42650, name = "亡者大军" },
        [67] = { type = "spell", spellId = 1247378, name = "腐化", },
        [68] = { type = "spell", spellId = 1247378, name = "腐化", charge = true },
        [69] = { type = "spell", spellId = 1233448, name = "黑暗突变" },
        [70] = { type = "spell", spellId = 343294, name = "灵魂收割" },
        [71] = { type = "spell", spellId = 43265, name = "枯萎凋零" },
        [72] = { type = "spell", spellId = 43265, name = "枯萎凋零", charge = true },
    },
}
Fuyutsui.MacrosList = {
    dynamicSpells = {},
    specialSpells = { [38] = "/castsequence reset=0.5 死亡之握,x", },
    staticSpells = {
        [1] = "亡者复生",
        [2] = "亡者大军",
        [3] = "凋零缠绕",
        [4] = "天灾打击",
        [5] = "扩散",
        [6] = "爆发",
        [7] = "脓疮打击",
        [8] = "腐化",
        [9] = "黑暗突变",
        [10] = "灵魂收割",
        [11] = "灵界打击",
        [12] = "[spec:1]心脏打击;[spec:3]天灾打击",
        [13] = "[@player]枯萎凋零",
        [14] = "死神的抚摸",
        [15] = "符文刃舞",
        [16] = "精髓分裂",
        [17] = "血液沸腾",
        [18] = "吸血鬼之血",
        [19] = "冰封之韧",
        [20] = "巫妖之躯",
        [21] = "[@cursor]反魔法领域",
        [22] = "[target=focus,exists] 窒息;窒息",
        [23] = "致盲冰雨",
        [24] = "血魔之握",
        [25] = "憎恶附肢",
        [26] = "死神印记",
        [27] = "冰川突进",
        [28] = "冰霜巨龙之怒",
        [29] = "冷酷严冬",
        [30] = "冰霜之柱",
        [31] = "冰霜打击",
        [32] = "凛风冲击",
        [33] = "冰霜之镰",
        [34] = "冰龙吐息",
        [35] = "湮灭",
        [36] = "符文武器增效",
        [37] = "符文打击",
        [39] = "吞噬",
        [40] = "item:241288\n/cast item:241289", -- 鲁莽药水
        [41] = "item:241304\n/cast item:241305", -- 银月城生命药水
    }
}
