if UnitClassBase("player") ~= "HUNTER" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },
        [21] = { type = "block", name = "敌人人数" },
        [22] = { type = "block", name = "爆发开关" },
        [23] = { type = "block", name = "输出模式" },
        [24] = { type = "block", name = "AOE开关" },

        [30] = { type = "spell", spellId = 53480, name = "牺牲咆哮" },
        [31] = { type = "spell", spellId = 109304, name = "意气风发" },
        [32] = { type = "spell", spellId = 19577, name = "胁迫" },
        [33] = { type = "spell", spellId = 5116, name = "震荡射击" },
        [34] = { type = "spell", spellId = 19801, name = "宁神射击" },
        [35] = { type = "spell", spellId = 187698, name = "焦油陷进" },
        [36] = { type = "spell", spellId = 1513, name = "恐吓野兽" },
        [37] = { type = "spell", spellId = 109248, name = "束缚射击" },
        [38] = { type = "spell", spellId = 195645, name = "摔绊" },

        [39] = { type = "spell", spellId = 34026, name = "杀戮命令" },
        [40] = { type = "spell", spellId = 34026, name = "杀戮命令", charge = true },
        [41] = { type = "spell", spellId = 217200, name = "倒刺射击" },
        [42] = { type = "spell", spellId = 217200, name = "倒刺射击", charge = true },
        [43] = { type = "spell", spellId = 147362, name = "反制射击" },
        [44] = { type = "spell", spellId = 19574, name = "狂野怒火" },
        [45] = { type = "spell", spellId = 1264359, name = "狂野鞭笞" },
        [46] = { type = "aura", name = "自然之友", auraName = "自然之友", showKey = "remaining" },
        [47] = { type = "aura", name = "猎人印记", auraName = "猎人印记", showKey = "remaining" },
        [48] = { type = "aura", name = "狂野怒火光环", auraName = "狂野怒火", showKey = "remaining" },

        [49] = { type = "block", name = "目标施法" },
        [50] = { type = "block", name = "目标施法可打断" },
        [51] = { type = "block", name = "焦点施法" },
        [52] = { type = "block", name = "焦点施法可打断" },

        [53] = { type = "block", name = "目标引导" },
        [54] = { type = "block", name = "目标引导可打断" },
        [55] = { type = "block", name = "焦点引导" },
        [56] = { type = "block", name = "焦点引导可打断" },
    },
    [2] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标施法" },
        [22] = { type = "block", name = "目标施法可打断" },
        [23] = { type = "block", name = "焦点施法" },
        [24] = { type = "block", name = "焦点施法可打断" },

        [25] = { type = "block", name = "目标引导" },
        [26] = { type = "block", name = "目标引导可打断" },
        [27] = { type = "block", name = "焦点引导" },
        [28] = { type = "block", name = "焦点引导可打断" },

        [30] = { type = "spell", spellId = 53480, name = "牺牲咆哮" },
        [31] = { type = "spell", spellId = 109304, name = "意气风发" },
        [32] = { type = "spell", spellId = 19577, name = "胁迫" },
        [33] = { type = "spell", spellId = 5116, name = "震荡射击" },
        [34] = { type = "spell", spellId = 19801, name = "宁神射击" },
        [35] = { type = "spell", spellId = 187698, name = "焦油陷进" },
        [36] = { type = "spell", spellId = 1513, name = "恐吓野兽" },
        [37] = { type = "spell", spellId = 109248, name = "束缚射击" },
        [38] = { type = "spell", spellId = 195645, name = "摔绊" },

        [39] = { type = "spell", spellId = 147362, name = "反制射击" },
        [40] = { type = "spell", spellId = 19434, name = "瞄准射击" },
        [41] = { type = "spell", spellId = 19434, name = "瞄准射击", charge = true },
        [42] = { type = "spell", spellId = 257044, name = "急速射击" },
        [43] = { type = "spell", spellId = 288613, name = "百发百中" },
    },
    [3] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标施法" },
        [22] = { type = "block", name = "目标施法可打断" },
        [23] = { type = "block", name = "焦点施法" },
        [24] = { type = "block", name = "焦点施法可打断" },

        [25] = { type = "block", name = "目标引导" },
        [26] = { type = "block", name = "目标引导可打断" },
        [27] = { type = "block", name = "焦点引导" },
        [28] = { type = "block", name = "焦点引导可打断" },
        
        [30] = { type = "spell", spellId = 53480, name = "牺牲咆哮" },
        [31] = { type = "spell", spellId = 109304, name = "意气风发" },
        [32] = { type = "spell", spellId = 19577, name = "胁迫" },
        [33] = { type = "spell", spellId = 5116, name = "震荡射击" },
        [34] = { type = "spell", spellId = 19801, name = "宁神射击" },
        [35] = { type = "spell", spellId = 187698, name = "焦油陷进" },
        [36] = { type = "spell", spellId = 1513, name = "恐吓野兽" },
        [37] = { type = "spell", spellId = 109248, name = "束缚射击" },
        [38] = { type = "spell", spellId = 195645, name = "摔绊" },

        [39] = { type = "spell", spellId = 1261193, name = "爆裂火铳" },
        [40] = { type = "spell", spellId = 1250646, name = "狩魂一击" },
        [41] = { type = "spell", spellId = 190925, name = "鱼叉猛刺" },
        [42] = { type = "spell", spellId = 186270, name = "猛禽一击" },
        [43] = { type = "spell", spellId = 259495, name = "野火炸弹" },
    },
}
Fuyutsui.MacrosList = {
    dynamicSpells = {},
    specialSpells = {},
    staticSpells = {
        [1] = "意气风发",
        [2] = "灵龟守护",
        [3] = "反制射击",
        [4] = "多重射击",
        [5] = "狂野怒火",
        [6] = "夺命射击",
        [7] = "百发百中",
        [8] = "爆炸射击",
        [9] = "荒野呼唤",
        [10] = "血溅十方",
        [11] = "治疗宠物",
        [12] = "倒刺射击",
        [13] = "杀戮命令",
        [14] = "眼镜蛇射击",
        [15] = "瞄准射击",
        [16] = "急速射击",
        [17] = "稳固射击",
        [18] = "哀恸箭",
        [19] = "猎人印记",
        [20] = "奥术射击",
        [21] = "奇美拉射击",
        [22] = "夺命黑鸦",
        [23] = "弹幕射击",
        [24] = "召唤宠物 1",
        [25] = "召唤宠物 2",
        [26] = "召唤宠物 3",
        [27] = "召唤宠物 4",
        [28] = "召唤宠物 5",
        [29] = "狂野鞭笞",
        [30] = "黑蚀箭",
        [31] = "[@cursor]乱射",
        [32] = "投掷手斧",
        [33] = "燎焰沥青",
        [34] = "爆裂火铳",
        [35] = "狩魂一击",
        [36] = "鱼叉猛刺",
        [37] = "猛禽一击",
        [38] = "野火炸弹",
        [39] = "牺牲咆哮",
    },
}
