if UnitClassBase("player") ~= "MAGE" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标施法" },
        [22] = { type = "block", name = "目标施法可打断" },
        [23] = { type = "block", name = "焦点施法" },
        [24] = { type = "block", name = "焦点施法可打断" },

        [25] = { type = "block", name = "目标引导" },
        [26] = { type = "block", name = "目标引导可打断" },
        [27] = { type = "block", name = "焦点引导" },
        [28] = { type = "block", name = "焦点引导可打断" },


    },
    [2] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标施法" },
        [22] = { type = "block", name = "目标施法可打断" },
        [23] = { type = "block", name = "焦点施法" },
        [24] = { type = "block", name = "焦点施法可打断" },

        [25] = { type = "block", name = "目标引导" },
        [26] = { type = "block", name = "目标引导可打断" },
        [27] = { type = "block", name = "焦点引导" },
        [28] = { type = "block", name = "焦点引导可打断" },

    },
    [3] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "施法技能" },
        [22] = { type = "block", name = "敌人人数" },

        [31] = { type = "aura", name = "热能真空", auraName = "热能真空", showKey = "remaining" },
        [32] = { type = "aura", name = "冰川尖刺！", auraName = "冰川尖刺！", showKey = "remaining" },
        [33] = { type = "aura", name = "冰冷智慧", auraName = "冰冷智慧", showKey = "remaining" },
        [34] = { type = "aura", name = "冰冻之雨", auraName = "冰冻之雨", showKey = "remaining" },
        [35] = { type = "aura", name = "寒冰指", auraName = "寒冰指", showKey = "remaining" },
        [36] = { type = "aura", name = "寒冰指层数", auraName = "寒冰指", showKey = "count" },

        [37] = { type = "block", name = "目标施法" },
        [38] = { type = "block", name = "目标施法可打断" },
        [39] = { type = "block", name = "焦点施法" },
        [40] = { type = "block", name = "焦点施法可打断" },

        [41] = { type = "block", name = "目标引导" },
        [42] = { type = "block", name = "目标引导可打断" },
        [43] = { type = "block", name = "焦点引导" },
        [44] = { type = "block", name = "焦点引导可打断" },
    },
}

Fuyutsui.MacrosList = {
    dynamicSpells = { "解除诅咒" },
    specialSpells = {},
    staticSpells = {
        [1] = "寒冰屏障",
        [2] = "解除诅咒",
        [3] = "强化隐形术",
        [4] = "超级新星",
        [5] = "冰锥术",
        [6] = "操控时间",
        [7] = "回归",
        [8] = "时间扭曲",
        [9] = "镜像",
        [10] = "法术反制",
        [11] = "闪现术",
        [12] = "缓落术",
        [13] = "魔爆术",
        [14] = "寒冰新星",
        [15] = "闪光术",
        [16] = "传送距离",
        [17] = "闪回",
        [18] = "强化隐形术",
        [19] = "冰霜新星",
        [20] = "龙息术",
        [21] = "群体隐形",
        [22] = "法术吸取",
        [23] = "[@cursor]暴风雪",

        [25] = "奥术智慧",
        [26] = "寒冰箭",
        [27] = "冰川尖刺",
        [28] = "冰枪术",
        [29] = "冰霜射线",
        [30] = "冰风暴",
        [31] = "寒冰宝珠",
        [32] = "霜火之箭",
        [33] = "彗星风暴",
        [34] = "急速冷却",
        [35] = "棱光护体",
        [36] = "奥术脉冲",
        [37] = "奥术弹幕",
        [38] = "大法师之触",
        [39] = "奥术飞弹",
        [40] = "奥术冲击",
        [41] = "奥术宝珠",
        [42] = "奥术涌动",
        [43] = "烈焰护体",
        [44] = "深寒凝冰",
        [45] = "燃烧",
        [46] = "[@cursor]流星",
        [47] = "火球术",
        [48] = "火焰冲击",
        [49] = "炎爆术",
        [50] = "[@cursor]烈焰风暴",
        [51] = "变形术",
        [52] = "霜火之箭",

        [54] = "灼烧",
        [55] = "造餐术",
    },
}
