if UnitClassBase("player") ~= "PRIEST" then return end
local addon, ns = ...

Fuyutsui.ClassBlocks = {
    [1] = {

        ["countBars"] = {
            { valueType = "charge", name = "苦修", minValue = 0, maxValue = 2, spellId = 47540 },
            { valueType = "charge", name = "真言术：耀", minValue = 0, maxValue = 2, spellId = 194509 }
        },

        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "施法技能" },
        [23] = { type = "block", name = "施法目标" },

        [24] = { type = "aura", name = "虚空之盾", auraName = "虚空之盾", showKey = "remaining" },
        [25] = { type = "aura", name = "圣光涌动", auraName = "圣光涌动", showKey = "remaining" },
        [26] = { type = "aura", name = "涌动层数", auraName = "圣光涌动", showKey = "count" },
        [27] = { type = "aura", name = "熵能裂隙", auraName = "熵能裂隙", showKey = "remaining" },
        [28] = { type = "aura", name = "暗影愈合", auraName = "暗影愈合", showKey = "remaining" },
        [29] = { type = "aura", name = "暗影层数", auraName = "暗影愈合", showKey = "count" },
        [30] = { type = "aura", name = "福音层数", auraName = "福音", showKey = "count" },
        [46] = { type = "aura", name = "祸福相依", auraName = "祸福相依", showKey = "remaining" },
        [47] = { type = "aura", name = "祸福层数", auraName = "祸福相依", showKey = "count" },

        [31] = { type = "spell", spellId = 8122, name = "心灵尖啸" },
        [32] = { type = "spell", spellId = 32375, name = "群体驱散" },
        [33] = { type = "spell", spellId = 527, name = "纯净术" },
        [34] = { type = "spell", spellId = 19236, name = "绝望祷言" },
        [35] = { type = "spell", spellId = 232633, name = "奥术洪流" },

        [36] = { type = "spell", spellId = 47540, name = "苦修" },
        [37] = { type = "spell", spellId = 47540, name = "苦修", charge = true },
        [38] = { type = "spell", spellId = 194509, name = "真言术：耀" },
        [39] = { type = "spell", spellId = 194509, name = "真言术：耀", charge = true },
        [40] = { type = "spell", spellId = 17, name = "真言术：盾" },
        [41] = { type = "spell", spellId = 62618, name = "真言术：障" },
        [42] = { type = "spell", spellId = 421453, name = "终极苦修" },
        [43] = { type = "spell", spellId = 472433, name = "福音" },
        [44] = { type = "spell", spellId = 8092, name = "心灵震爆" },
        [45] = { type = "spell", spellId = 32379, name = "暗言术：灭" },

        [70] = {
            type = "group",
            num = 5,
            healthPercent = 1,
            role = 2,
            dispel = 3,
            auras = {
                [4] = { 194384 },      -- 救赎, 194384
                [5] = { 17, 1253593 }, -- 真言术：盾, 虚空护盾, 17, 1253593
            },
        },
    },
    [2] = {
        ["countBars"] = {
            { valueType = "charge", name = "愈合祷言", minValue = 0, maxValue = 2, spellId = 33076 },
            { valueType = "charge", name = "圣言术：静", minValue = 0, maxValue = 2, spellId = 2050 }
        },

        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [22] = { type = "block", name = "施法技能" },
        [23] = { type = "block", name = "施法目标" },

        [25] = { type = "aura", name = "织光者", auraName = "织光者", showKey = "remaining" },
        [26] = { type = "aura", name = "织光者层数", auraName = "织光者", showKey = "count" },
        [27] = { type = "aura", name = "圣光涌动", auraName = "圣光涌动", showKey = "remaining" },
        [28] = { type = "aura", name = "祈福", auraName = "祈福", showKey = "remaining" },

        [31] = { type = "spell", spellId = 8122, name = "心灵尖啸" },
        [32] = { type = "spell", spellId = 32375, name = "群体驱散" },
        [33] = { type = "spell", spellId = 527, name = "纯净术" },
        [34] = { type = "spell", spellId = 19236, name = "绝望祷言" },
        [35] = { type = "spell", spellId = 232633, name = "奥术洪流" },

        [36] = { type = "spell", spellId = 33076, name = "愈合祷言" },
        [37] = { type = "spell", spellId = 33076, name = "愈合祷言", charge = true },
        [38] = { type = "spell", spellId = 2050, name = "圣言术：静" },
        [39] = { type = "spell", spellId = 2050, name = "圣言术：静" },
        [40] = { type = "spell", spellId = 88625, name = "圣言术：罚" },
        [41] = { type = "spell", spellId = 200183, name = "神圣化身" },
        [42] = { type = "spell", spellId = 14914, name = "神圣之火" },
        [43] = { type = "spell", spellId = 120517, name = "光晕" },
        [44] = { type = "spell", spellId = 64843, name = "神圣赞美诗" },

        [70] = {
            type = "group",
            num = 5,
            healthPercent = 1,
            role = 2,
            dispel = 3,
            auras = {
                [4] = { 41635 }, -- 愈合祷言, 41635
                [5] = { 139 },   -- 恢复, 139
            },
        },

    },
    [3] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [36] = { type = "spell", spellId = 8092, name = "心灵震爆" },
        [37] = { type = "spell", spellId = 32379, name = "暗言术：灭" },
        [38] = { type = "spell", spellId = 263165, name = "虚空洪流" },
        [39] = { type = "spell", spellId = 228260, name = "虚空形态" },
        [40] = { type = "spell", spellId = 1227280, name = "触须猛击" },
        [41] = { type = "spell", spellId = 15286, name = "吸血鬼的拥抱" },
        [42] = { type = "spell", spellId = 120644, name = "光晕" },
        [43] = { type = "spell", spellId = 1242173, name = "虚空齐射", forcedKnown = true },

    },
}

Fuyutsui.MacrosList = {
    dynamicSpells = { "苦修", "快速治疗", "真言术：盾", "愈合祷言", "纯净术", "圣言术：静" },
    specialSpells = { [36] = "/castsequence reset=3 真言术：耀,x", },
    staticSpells = {
        [1] = "心灵震爆",
        [2] = "惩击",
        [3] = "暗言术：痛",
        [4] = "真言术：韧",
        [5] = "神圣新星",
        [6] = "苦修",
        [7] = "真言术：耀",
        [8] = "福音",
        [9] = "终极苦修",
        [10] = "绝望祷言",
        [11] = "暗言术：灭",
        [12] = "吸血鬼之触",
        [13] = "[nostance:1]暗影形态",
        [14] = "暗言术：癫",
        [15] = "精神鞭笞",
        [16] = "虚空形态",
        [17] = "虚空洪流",
        [18] = "触须猛击",
        [19] = "虚空冲击",
        [20] = "虚空齐射",
        [21] = "圣言术：罚",
        [22] = "神圣之火",
        [23] = "治疗祷言",
        [24] = "神圣化身",
        [25] = "奥术洪流",
        [26] = "心灵尖啸",
        [27] = "[@cursor]群体驱散",
        [28] = "[@cursor]真言术：障",
        [29] = "神圣赞美诗",
        [30] = "光晕",
        [31] = "纯净术",
        [32] = "快速治疗",
        [33] = "真言术：盾",
        [34] = "愈合祷言",
        [35] = "圣言术：静",
    },
}
