if UnitClassBase("player") ~= "ROGUE" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标施法" },
        [22] = { type = "block", name = "目标施法可打断" },
        [23] = { type = "block", name = "焦点施法" },
        [24] = { type = "block", name = "焦点施法可打断" },

        [25] = { type = "block", name = "目标引导" },
        [26] = { type = "block", name = "目标引导可打断" },
        [27] = { type = "block", name = "焦点引导" },
        [28] = { type = "block", name = "焦点引导可打断" },

        [31] = { type = "spell", spellId = 5938, name = "毒刃" },
        [32] = { type = "spell", spellId = 2094, name = "致盲" },
        [33] = { type = "spell", spellId = 1966, name = "佯攻" },
        [34] = { type = "spell", spellId = 1856, name = "消失" },
        [35] = { type = "spell", spellId = 1833, name = "偷袭" },
        [36] = { type = "spell", spellId = 114018, name = "潜伏帷幕" },
        [37] = { type = "spell", spellId = 381623, name = "菊花茶" },
        [38] = { type = "spell", spellId = 5277, name = "闪避" },
        [39] = { type = "spell", spellId = 185311, name = "猩红之瓶" },
        [40] = { type = "spell", spellId = 1725, name = "扰乱" },
        [41] = { type = "spell", spellId = 2983, name = "疾跑" },
        [42] = { type = "spell", spellId = 1776, name = "凿击" },
        [43] = { type = "spell", spellId = 408, name = "肾击" },
        [44] = { type = "spell", spellId = 31224, name = "暗影斗篷" },
        [45] = { type = "spell", spellId = 1766, name = "脚踢" },

        [46] = { type = "spell", spellId = 360194, name = "死亡印记" },
        [47] = { type = "spell", spellId = 1293340, name = "死亡印记" },
        [48] = { type = "spell", spellId = 703, name = "锁喉" },
        [49] = { type = "spell", spellId = 385627, name = "君王之灾" },
        [50] = { type = "spell", spellId = 36554, name = "暗影步" },

    },
    [2] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标施法" },
        [22] = { type = "block", name = "目标施法可打断" },
        [23] = { type = "block", name = "焦点施法" },
        [24] = { type = "block", name = "焦点施法可打断" },

        [25] = { type = "block", name = "目标引导" },
        [26] = { type = "block", name = "目标引导可打断" },
        [27] = { type = "block", name = "焦点引导" },
        [28] = { type = "block", name = "焦点引导可打断" },

        [31] = { type = "spell", spellId = 5938, name = "毒刃" },
        [32] = { type = "spell", spellId = 2094, name = "致盲" },
        [33] = { type = "spell", spellId = 1966, name = "佯攻" },
        [34] = { type = "spell", spellId = 1856, name = "消失" },
        [35] = { type = "spell", spellId = 1833, name = "偷袭" },
        [36] = { type = "spell", spellId = 114018, name = "潜伏帷幕" },
        [37] = { type = "spell", spellId = 381623, name = "菊花茶" },
        [38] = { type = "spell", spellId = 5277, name = "闪避" },
        [39] = { type = "spell", spellId = 185311, name = "猩红之瓶" },
        [40] = { type = "spell", spellId = 1725, name = "扰乱" },
        [41] = { type = "spell", spellId = 2983, name = "疾跑" },
        [42] = { type = "spell", spellId = 1776, name = "凿击" },
        [43] = { type = "spell", spellId = 408, name = "肾击" },
        [44] = { type = "spell", spellId = 31224, name = "暗影斗篷" },
        [45] = { type = "spell", spellId = 1766, name = "脚踢" },

        [46] = { type = "spell", spellId = 13750, name = "冲动" },
        [47] = { type = "spell", spellId = 51690, name = "影舞步" },
        [48] = { type = "spell", spellId = 271877, name = "刀锋冲刺" },
        [49] = { type = "spell", spellId = 315341, name = "正中眉心" },
        [50] = { type = "spell", spellId = 13877, name = "剑刃乱舞" },
        [51] = { type = "spell", spellId = 195475, name = "抓钩" },
        [52] = { type = "spell", spellId = 195475, name = "抓钩", charge = true },
        [53] = { type = "spell", spellId = 1214909, name = "命运骨骰" },


    },
    [3] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标施法" },
        [22] = { type = "block", name = "目标施法可打断" },
        [23] = { type = "block", name = "焦点施法" },
        [24] = { type = "block", name = "焦点施法可打断" },

        [25] = { type = "block", name = "目标引导" },
        [26] = { type = "block", name = "目标引导可打断" },
        [27] = { type = "block", name = "焦点引导" },
        [28] = { type = "block", name = "焦点引导可打断" },

        [31] = { type = "spell", spellId = 5938, name = "毒刃" },
        [32] = { type = "spell", spellId = 2094, name = "致盲" },
        [33] = { type = "spell", spellId = 1966, name = "佯攻" },
        [34] = { type = "spell", spellId = 1856, name = "消失" },
        [35] = { type = "spell", spellId = 1833, name = "偷袭" },
        [36] = { type = "spell", spellId = 114018, name = "潜伏帷幕" },
        [37] = { type = "spell", spellId = 381623, name = "菊花茶" },
        [38] = { type = "spell", spellId = 5277, name = "闪避" },
        [39] = { type = "spell", spellId = 185311, name = "猩红之瓶" },
        [40] = { type = "spell", spellId = 1725, name = "扰乱" },
        [41] = { type = "spell", spellId = 2983, name = "疾跑" },
        [42] = { type = "spell", spellId = 1776, name = "凿击" },
        [43] = { type = "spell", spellId = 408, name = "肾击" },
        [44] = { type = "spell", spellId = 31224, name = "暗影斗篷" },
        [45] = { type = "spell", spellId = 1766, name = "脚踢" },
        [46] = { type = "spell", spellId = 36554, name = "暗影步" },
        [47] = { type = "spell", spellId = 280719, name = "影分身" },
        [48] = { type = "spell", spellId = 121471, name = "暗影之刃" },
        [49] = { type = "spell", spellId = 185313, name = "暗影之舞" },
        [50] = { type = "spell", spellId = 185313, name = "暗影之舞", charge = true },


    },
}
Fuyutsui.MacrosList = {
    dynamicSpells = {},
    specialSpells = {},
    staticSpells = {
        [1] = "毒刃",
        [2] = "致盲",
        [3] = "暗影斗篷",
        [4] = "凿击",
        [5] = "嫁祸诀窍",
        [6] = "闪避",
        [7] = "迟钝药膏",
        [8] = "萎缩药膏",
        [9] = "菊花茶",
        [10] = "肾击",
        [11] = "佯攻",
        [12] = "偷袭",
        [13] = "消失",
        [14] = "切割",
        [15] = "潜伏帷幕",
        [16] = "扰乱",
        [17] = "猩红之瓶",
        [18] = "疾跑",
        [19] = "闷棍",
        [20] = "速效药膏",
        [21] = "致伤药膏",
        [22] = "夺命药膏",
        [23] = "增效药膏",
        [24] = "减速药膏",
        [25] = "刀扇",
        [26] = "死亡印记",
        [27] = "死亡印记",
        [28] = "锁喉",
        [29] = "剧毒之刃",
        [30] = "割裂",
        [31] = "毁伤",
        [32] = "君王之灾",
        [33] = "毒伤",
        [34] = "暗影步",
        [35] = "猩红风暴",
        [36] = "伏击",
        [37] = "脚踢",
        [38] = "冲动",
        [39] = "影舞步",
        [40] = "正中眉心",
        [41] = "刀锋冲刺",
        [42] = "手枪射击",
        [43] = "剑刃乱舞",
        [44] = "抓钩",
        [45] = "命运骨骰",
        [46] = "斩击",
        [47] = "时运继延",
        [48] = "伺机待发",
        [49] = "黑火药",
        [50] = "影分身",
        [51] = "暗影之刃",
        [52] = "背刺",
        [53] = "暗影之舞",
        [54] = "袖剑风暴",
        [55] = "暗影打击",
        [56] = "飞镖投掷",
        [57] = "赤喉之咬",
        [58] = "影袭",
        [59] = "致命一击",
    },
}
