if UnitClassBase("player") ~= "WARLOCK" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "灵魂碎片" },
        [22] = { type = "block", name = "施法技能" },

        [23] = { type = "block", name = "目标施法" },
        [24] = { type = "block", name = "目标施法可打断" },
        [25] = { type = "block", name = "焦点施法" },
        [26] = { type = "block", name = "焦点施法可打断" },

        [27] = { type = "block", name = "目标引导" },
        [28] = { type = "block", name = "目标引导可打断" },
        [29] = { type = "block", name = "焦点引导" },
        [30] = { type = "block", name = "焦点引导可打断" },


        [31] = { type = "spell", spellId = 5782, name = "恐惧" },
        [32] = { type = "spell", spellId = 6789, name = "死亡缠绕" },
        [33] = { type = "spell", spellId = 20707, name = "灵魂石" },
        [34] = { type = "spell", spellId = 30283, name = "暗影之怒" },
        [35] = { type = "spell", spellId = 333889, name = "邪能统御" },
        [36] = { type = "spell", spellId = 108416, name = "黑暗契约" },
        [37] = { type = "spell", spellId = 111771, name = "恶魔传送门" },
        [38] = { type = "spell", spellId = 127174, name = "虚弱灾厄" },
        [39] = { type = "spell", spellId = 1271802, name = "语言灾厄" },
        [40] = { type = "spell", spellId = 48018, name = "恶魔法阵" },
        [41] = { type = "spell", spellId = 48020, name = "恶魔法阵：传送" },

        [42] = { type = "spell", spellId = 205180, name = "召唤黑眼" },
        [43] = { type = "spell", spellId = 48181, name = "鬼影缠身" },
        [44] = { type = "spell", spellId = 1257052, name = "幽冥收割" },
        [45] = { type = "spell", spellId = 442726, name = "怨毒" },

    },
    [2] = {

        ["countBars"] = {
            { valueType = "castCount", name = "内爆", minValue = 0, maxValue = 20, spellId = 196277 }
        },

        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "治疗石冷却" },
        [22] = { type = "block", name = "大红冷却" },
        [23] = { type = "block", name = "灵魂碎片" },
        [24] = { type = "block", name = "施法技能" },

        [52] = { type = "block", name = "目标施法" },
        [53] = { type = "block", name = "目标施法可打断" },
        [54] = { type = "block", name = "焦点施法" },
        [55] = { type = "block", name = "焦点施法可打断" },

        [56] = { type = "block", name = "目标引导" },
        [57] = { type = "block", name = "目标引导可打断" },
        [58] = { type = "block", name = "焦点引导" },
        [59] = { type = "block", name = "焦点引导可打断" },

        [31] = { type = "spell", spellId = 5782, name = "恐惧" },
        [32] = { type = "spell", spellId = 6789, name = "死亡缠绕" },
        [33] = { type = "spell", spellId = 20707, name = "灵魂石" },
        [34] = { type = "spell", spellId = 30283, name = "暗影之怒" },
        [35] = { type = "spell", spellId = 333889, name = "邪能统御" },
        [36] = { type = "spell", spellId = 108416, name = "黑暗契约" },
        [37] = { type = "spell", spellId = 111771, name = "恶魔传送门" },
        [38] = { type = "spell", spellId = 127174, name = "虚弱灾厄" },
        [39] = { type = "spell", spellId = 1271802, name = "语言灾厄" },
        [40] = { type = "spell", spellId = 48018, name = "恶魔法阵" },
        [41] = { type = "spell", spellId = 48020, name = "恶魔法阵：传送" },

        [42] = { type = "spell", spellId = 196277, name = "内爆" },
        [43] = { type = "spell", spellId = 265187, name = "召唤恶魔暴君" },
        [44] = { type = "spell", spellId = 1276467, name = "魔典：邪能破坏者" },
        [45] = { type = "spell", spellId = 105174, name = "古尔丹之手" },
        [46] = { type = "spell", spellId = 1276672, name = "召唤末日守卫" },
        [47] = { type = "spell", spellId = 104316, name = "召唤恐惧猎犬" },
        [48] = { type = "spell", spellId = 264187, name = "恶魔之箭" },
        [49] = { type = "spell", spellId = 1276452, name = "魔典：小鬼领主" },
        [50] = { type = "spell", spellId = 388215, name = "吞噬魔法" },
        [51] = { type = "spell", spellId = 30146, name = "召唤恶魔卫士" },

    },
    [3] = {
        [1] = { type = "block", name = "锚点" },
        [2] = { type = "block", name = "职业" },
        [3] = { type = "block", name = "专精" },
        [4] = { type = "block", name = "有效性" },
        [5] = { type = "block", name = "战斗" },
        [6] = { type = "block", name = "移动" },
        [7] = { type = "block", name = "施法" },
        [8] = { type = "block", name = "引导" },
        [9] = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标施法" },
        [22] = { type = "block", name = "目标施法可打断" },
        [23] = { type = "block", name = "焦点施法" },
        [24] = { type = "block", name = "焦点施法可打断" },

        [25] = { type = "block", name = "目标引导" },
        [26] = { type = "block", name = "目标引导可打断" },
        [27] = { type = "block", name = "焦点引导" },
        [28] = { type = "block", name = "焦点引导可打断" },
        
        [29] = { type = "block", name = "灵魂碎片" },
        [30] = { type = "block", name = "施法技能" },

        [31] = { type = "spell", spellId = 5782, name = "恐惧" },
        [32] = { type = "spell", spellId = 6789, name = "死亡缠绕" },
        [33] = { type = "spell", spellId = 20707, name = "灵魂石" },
        [34] = { type = "spell", spellId = 30283, name = "暗影之怒" },
        [35] = { type = "spell", spellId = 333889, name = "邪能统御" },
        [36] = { type = "spell", spellId = 108416, name = "黑暗契约" },
        [37] = { type = "spell", spellId = 111771, name = "恶魔传送门" },
        [38] = { type = "spell", spellId = 127174, name = "虚弱灾厄" },
        [39] = { type = "spell", spellId = 1271802, name = "语言灾厄" },
        [40] = { type = "spell", spellId = 48018, name = "恶魔法阵" },
        [41] = { type = "spell", spellId = 48020, name = "恶魔法阵：传送" },

        [42] = { type = "spell", spellId = 1122, name = "召唤地狱火" },
        [43] = { type = "spell", spellId = 6353, name = "灵魂之火" },
        [44] = { type = "spell", spellId = 17962, name = "燃烧" },
        [45] = { type = "spell", spellId = 17962, name = "燃烧", charge = true },

    },
}

Fuyutsui.MacrosList = {
    dynamicSpells = {},
    specialSpells = {},
    staticSpells = {
        [1] = "恐惧",
        [2] = "死亡缠绕",
        [3] = "[@cursor]暗影之怒",
        [4] = "内爆",
        [5] = "召唤恶魔暴君",
        [6] = "魔典：邪能破坏者",
        [7] = "召唤末日守卫",
        [8] = "古尔丹之手",
        [9] = "召唤恐惧猎犬",
        [10] = "召唤恶魔卫士",
        [11] = "恶魔之箭",
        [12] = "暗影箭",
        [13] = "召唤地狱猎犬",
        [14] = "召唤小鬼",
        [15] = "虚弱灾厄",
        [16] = "语言灾厄",
        [17] = "陨灭",
        [18] = "狱火箭",
        [19] = "灵魂石",
        [20] = "邪能统御",
        [21] = "黑暗契约",
        [22] = "恶魔之箭",
        [23] = "魔典：小鬼领主",
        [24] = "法术封锁",
        [25] = "吞噬魔法",
        [26] = "爆燃冲刺",
        [27] = "放逐术",
        [28] = "疲劳诅咒",
        [29] = "语言诅咒",
        [30] = "恶魔传送门",
        [31] = "灵魂燃烧",
        [32] = "恐惧嚎叫",
        [33] = "恶魔法阵",
        [34] = "恶魔法阵：传送",
        [35] = "制造灵魂之井",
        [36] = "召唤仪式",
        [37] = "腐蚀术",
        [38] = "吸取生命",
        [39] = "召唤黑眼",
        [40] = "痛苦无常",
        [41] = "幽冥收割",
        [42] = "腐蚀之种",
        [43] = "痛楚",
        [44] = "鬼影缠身",
        [45] = "枯萎",
        [46] = "怨毒",
        [47] = "召唤地狱火",
        [48] = "暗影灼烧",
        [49] = "混乱之箭",
        [50] = "火焰之雨",
        [51] = "灵魂之火",
        [52] = "烧尽",
        [53] = "燃烧",
        [54] = "献祭",
        [55] = "引导恶魔之火",
        [56] = "浩劫",
        [57] = "火焰之雨",
        [58] = "大灾变",
        [59] = "吸取灵魂",
        [60] = "召唤虚空行者",
        [61] = "召唤萨亚德",
    },
}
