if UnitClassBase("player") ~= "WARRIOR" then return end
local addon, ns = ...
Fuyutsui.ClassBlocks = {
    [1] = {
        [1]  = { type = "block", name = "锚点" },
        [2]  = { type = "block", name = "职业" },
        [3]  = { type = "block", name = "专精" },
        [4]  = { type = "block", name = "有效性" },
        [5]  = { type = "block", name = "战斗" },
        [6]  = { type = "block", name = "移动" },
        [7]  = { type = "block", name = "施法" },
        [8]  = { type = "block", name = "引导" },
        [9]  = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "敌人人数" },
        [23] = { type = "aura", name = "斩杀高亮", auraName = "斩杀高亮", showKey = "remaining" },
        [24] = { type = "aura", name = "英勇打击高亮", auraName = "英勇打击高亮", showKey = "remaining" },
        


        [31] = { type = "spell", spellId = 202168, name = "胜利在望" },
        [32] = { type = "spell", spellId = 376079, name = "勇士之矛" },
        [33] = { type = "spell", spellId = 6544, name = "英勇飞跃" },
        [34] = { type = "spell", spellId = 97462, name = "集结呐喊" },
        [35] = { type = "spell", spellId = 46968, name = "震荡波" },
        [36] = { type = "spell", spellId = 107570, name = "风暴之锤" },
        [37] = { type = "spell", spellId = 384110, name = "破裂投掷" },
        [38] = { type = "spell", spellId = 64382, name = "碎裂投掷" },
        [39] = { type = "spell", spellId = 5246, name = "破胆怒吼" },
        [40] = { type = "spell", spellId = 7384, name = "压制" },
        [41] = { type = "spell", spellId = 7384, name = "压制", charge = true },
        [42] = { type = "spell", spellId = 163201, name = "斩杀" },
        [43] = { type = "spell", spellId = 845, name = "顺劈斩" },
        [44] = { type = "spell", spellId = 12294, name = "致死打击" },
        [45] = { type = "spell", spellId = 167105, name = "巨人打击" },
        [46] = { type = "spell", spellId = 436358, name = "崩摧" },      
    },
    [2] = {
        [1]  = { type = "block", name = "锚点" },
        [2]  = { type = "block", name = "职业" },
        [3]  = { type = "block", name = "专精" },
        [4]  = { type = "block", name = "有效性" },
        [5]  = { type = "block", name = "战斗" },
        [6]  = { type = "block", name = "移动" },
        [7]  = { type = "block", name = "施法" },
        [8]  = { type = "block", name = "引导" },
        [9]  = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },
        [21] = { type = "block", name = "敌人人数" },

        [31] = { type = "spell", spellId = 202168, name = "胜利在望" },
        [32] = { type = "spell", spellId = 376079, name = "勇士之矛" },
        [33] = { type = "spell", spellId = 6544, name = "英勇飞跃" },
        [34] = { type = "spell", spellId = 97462, name = "集结呐喊" },
        [35] = { type = "spell", spellId = 46968, name = "震荡波" },
        [36] = { type = "spell", spellId = 107570, name = "风暴之锤" },
        [37] = { type = "spell", spellId = 384110, name = "破裂投掷" },
        [38] = { type = "spell", spellId = 64382, name = "碎裂投掷" },
        [39] = { type = "spell", spellId = 5246, name = "破胆怒吼" },
        [40] = { type = "spell", spellId = 1719, name = "鲁莽" },
    },
    [3] = {
        [1]  = { type = "block", name = "锚点" },
        [2]  = { type = "block", name = "职业" },
        [3]  = { type = "block", name = "专精" },
        [4]  = { type = "block", name = "有效性" },
        [5]  = { type = "block", name = "战斗" },
        [6]  = { type = "block", name = "移动" },
        [7]  = { type = "block", name = "施法" },
        [8]  = { type = "block", name = "引导" },
        [9]  = { type = "block", name = "蓄力" },
        [10] = { type = "block", name = "蓄力层数" },
        [11] = { type = "block", name = "生命值" },
        [12] = { type = "block", name = "能量值" },
        [13] = { type = "block", name = "一键辅助" },
        [14] = { type = "block", name = "法术失败" },
        [15] = { type = "block", name = "目标类型" },
        [16] = { type = "block", name = "队伍类型" },
        [17] = { type = "block", name = "队伍人数" },
        [18] = { type = "block", name = "首领战" },
        [19] = { type = "block", name = "难度" },
        [20] = { type = "block", name = "英雄天赋" },

        [21] = { type = "block", name = "目标生命值" },
        [22] = { type = "block", name = "敌人人数" },

        [25] = { type = "aura", name = "盾牌格挡", auraName = "盾牌格挡", showKey = "remaining" },

        [31] = { type = "spell", spellId = 202168, name = "胜利在望" },
        [32] = { type = "spell", spellId = 376079, name = "勇士之矛" },
        [33] = { type = "spell", spellId = 6544, name = "英勇飞跃" },
        [34] = { type = "spell", spellId = 97462, name = "集结呐喊" },
        [35] = { type = "spell", spellId = 46968, name = "震荡波" },
        [36] = { type = "spell", spellId = 107570, name = "风暴之锤" },
        [37] = { type = "spell", spellId = 384110, name = "破裂投掷" },
        [38] = { type = "spell", spellId = 64382, name = "碎裂投掷" },
        [39] = { type = "spell", spellId = 5246, name = "破胆怒吼" },

        [40] = { type = "spell", spellId = 2565, name = "盾牌格挡" },
        [41] = { type = "spell", spellId = 2565, name = "盾牌格挡", charge = true },
        [42] = { type = "spell", spellId = 385952, name = "盾牌冲锋" },
        [43] = { type = "spell", spellId = 107574, name = "天神下凡" },
        [44] = { type = "spell", spellId = 1160, name = "挫志怒吼" },

    },
}

Fuyutsui.MacrosList = {
    dynamicSpells = {},
    specialSpells = {},
    staticSpells = {
        [1] = "英勇投掷",
        [2] = "战斗怒吼",
        [3] = "猛击",
        [4] = "撕裂",
        [5] = "斩杀",
        [6] = "剑刃风暴",
        [7] = "崩摧",
        [8] = "致死打击",
        [9] = "巨人打击",
        [10] = "顺劈斩",
        [11] = "压制",
        [12] = "横扫攻击",
        [13] = "天神下凡",
        [14] = "旋风斩",
        [15] = "斩杀",
        [16] = "嗜血",
        [17] = "暴怒",
        [18] = "奥丁之怒",
        [19] = "怒击",
        [20] = "雷霆一击",
        [21] = "复仇",
        [22] = "胜利在望",
        [23] = "勇士之矛",
        [24] = "英勇飞跃",
        [25] = "集结呐喊",
        [26] = "震荡波",
        [27] = "风暴之锤",
        [28] = "盾牌猛击",
        [29] = "破裂投掷",
        [30] = "碎裂投掷",
        [31] = "破胆怒吼",
        [32] = "鲁莽",
        [33] = "盾牌格挡",
        [34] = "盾牌冲锋",
        [35] = "挫志怒吼",
        [36] = "无视苦痛",
        [37] = "破坏者",
    },
}
